
var CppBenchmark = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(CppBenchmark) {
  CppBenchmark = CppBenchmark || {};


var e;e||(e=typeof CppBenchmark !== 'undefined' ? CppBenchmark : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},e),da="object"===typeof window,t="function"===typeof importScripts,ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u="",fa,v,w,fs,y,ha;
if(ea)u=t?require("path").dirname(u)+"/":__dirname+"/",ha=()=>{y||(fs=require("fs"),y=require("path"))},fa=function(a,b){ha();a=y.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},w=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},v=(a,b,c)=>{ha();a=y.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;
}),e.inspect=function(){return"[Emscripten Module object]"};else if(da||t)t?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):u="",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
v=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var z=e.printErr||console.warn.bind(console);Object.assign(e,ca);ca=null;var A;e.wasmBinary&&(A=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&B("no native wasm support detected");
var ia,ja=!1,ka="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;function la(a,b,c){var d=C;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}
var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function na(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&ma)return ma.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=E[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function oa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)E[b>>1]=a.charCodeAt(f),b+=2;E[b>>1]=0;return b-d}function pa(a){return 2*a.length}
function qa(a,b){for(var c=0,d="";!(c>=b/4);){var f=G[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function ra(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ta,H,C,E,D,G,I,ua,va,wa,xa=[],ya=[],za=[];function Aa(){var a=e.preRun.shift();xa.unshift(a)}var J=0,Ba=null,L=null;e.preloadedImages={};e.preloadedAudios={};function B(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";z(a);ja=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function Ca(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="binds.wasm";if(!Ca()){var Da=M;M=e.locateFile?e.locateFile(Da,u):u+Da}function Ea(){var a=M;try{if(a==M&&A)return new Uint8Array(A);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}catch(b){B(b)}}
function Fa(){if(!A&&(da||t)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ea()});if(v)return new Promise(function(a,b){v(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ea()})}
function Ga(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.I;"number"===typeof c?void 0===b.C?N(c)():N(c)(b.C):c(void 0===b.C?null:b.C)}}}var O=[];function N(a){var b=O[a];b||(a>=O.length&&(O.length=a+1),O[a]=b=wa.get(a));return b}function Ha(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ia=void 0;function P(a){for(var b="";C[a];)b+=Ia[C[a++]];return b}var Q={},R={},S={};
function Ja(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ka(a,b){a=Ja(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function La(a){var b=Error,c=Ka(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ma=void 0;function T(a){throw new Ma(a);}var Pa=void 0;
function Qa(a,b){function c(k){k=b(k);if(k.length!==d.length)throw new Pa("Mismatched type converter count");for(var h=0;h<d.length;++h)U(d[h],k[h])}var d=[];d.forEach(function(k){S[k]=a});var f=Array(a.length),g=[],n=0;a.forEach(function(k,h){R.hasOwnProperty(k)?f[h]=R[k]:(g.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(function(){f[h]=R[k];++n;n===g.length&&c(f)}))});0===g.length&&c(f)}
function U(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.G)return;T("Cannot register type '"+d+"' twice")}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}var Ra=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Sa(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ra.length?Ra.pop():V.length;V[b]={H:1,value:a};return b}}function Ta(a){return this.fromWireType(I[a>>2])}function Ua(a,b){switch(b){case 2:return function(c){return this.fromWireType(ua[c>>2])};case 3:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Va(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ka(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Wa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Xa(a,b){var c=e;if(void 0===c[a].A){var d=c[a];c[a]=function(){c[a].A.hasOwnProperty(arguments.length)||T("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].A+")!");return c[a].A[arguments.length].apply(this,arguments)};c[a].A=[];c[a].A[d.F]=d}}
function Ya(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].A&&void 0!==e[a].A[c])&&T("Cannot register public name '"+a+"' twice"),Xa(a,a),e.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].A[c]=b):(e[a]=b,void 0!==c&&(e[a].K=c))}function Za(a,b){for(var c=[],d=0;d<a;d++)c.push(G[(b>>2)+d]);return c}
function $a(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=e["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=N(b).apply(null,c);return d}}function ab(a,b){a=P(a);var c=a.includes("j")?$a(a,b):N(b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var bb=void 0;function cb(a){a=db(a);var b=P(a);W(a);return b}
function eb(a,b){function c(g){f[g]||R[g]||(S[g]?S[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new bb(a+": "+d.map(cb).join([", "]));}function fb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return C[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var gb;
gb=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function hb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ea)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){B("randomDevice")}}function X(a,b){X.D||(X.D=hb());for(var c=0;c<b;c++)H[a+c>>0]=X.D();return 0}for(var ib=Array(256),Y=0;256>Y;++Y)ib[Y]=String.fromCharCode(Y);
Ia=ib;Ma=e.BindingError=La("BindingError");Pa=e.InternalError=La("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};bb=e.UnboundTypeError=La("UnboundTypeError");
var lb={l:function(){},k:function(a,b,c,d,f){var g=Ha(c);b=P(b);U(a,{name:b,fromWireType:function(n){return!!n},toWireType:function(n,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(n){if(1===c)var k=H;else if(2===c)k=E;else if(4===c)k=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[n>>g])},B:null})},j:function(a,b){b=P(b);U(a,{name:b,fromWireType:function(c){c||T("Cannot use deleted val. handle = "+c);var d=V[c].value;4<c&&0===--V[c].H&&(V[c]=
void 0,Ra.push(c));return d},toWireType:function(c,d){return Sa(d)},argPackAdvance:8,readValueFromPointer:Ta,B:null})},f:function(a,b,c){c=Ha(c);b=P(b);U(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){return f},argPackAdvance:8,readValueFromPointer:Ua(b,c),B:null})},e:function(a,b,c,d,f,g){var n=Za(b,c);a=P(a);f=ab(d,f);Ya(a,function(){eb("Cannot call "+a+" due to unbound types",n)},b-1);Qa(n,function(k){var h=[k[0],null].concat(k.slice(1)),p=k=a,q=f,m=h.length;2>m&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var r=null!==h[1]&&!1,x=!1,l=1;l<h.length;++l)if(null!==h[l]&&void 0===h[l].B){x=!0;break}var Na="void"!==h[0].name,F="",K="";for(l=0;l<m-2;++l)F+=(0!==l?", ":"")+"arg"+l,K+=(0!==l?", ":"")+"arg"+l+"Wired";p="return function "+Ja(p)+"("+F+") {\nif (arguments.length !== "+(m-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(m-2)+" args!');\n}\n";x&&(p+="var destructors = [];\n");var Oa=x?"destructors":"null";F="throwBindingError invoker fn runDestructors retType classParam".split(" ");
q=[T,q,g,Wa,h[0],h[1]];r&&(p+="var thisWired = classParam.toWireType("+Oa+", this);\n");for(l=0;l<m-2;++l)p+="var arg"+l+"Wired = argType"+l+".toWireType("+Oa+", arg"+l+"); // "+h[l+2].name+"\n",F.push("argType"+l),q.push(h[l+2]);r&&(K="thisWired"+(0<K.length?", ":"")+K);p+=(Na?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";if(x)p+="runDestructors(destructors);\n";else for(l=r?1:2;l<h.length;++l)m=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==h[l].B&&(p+=m+"_dtor("+m+"); // "+h[l].name+
"\n",F.push(m+"_dtor"),q.push(h[l].B));Na&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");F.push(p+"}\n");h=Va(F).apply(null,q);l=b-1;if(!e.hasOwnProperty(k))throw new Pa("Replacing nonexistant public symbol");void 0!==e[k].A&&void 0!==l?e[k].A[l]=h:(e[k]=h,e[k].F=l);return[]})},b:function(a,b,c,d,f){b=P(b);-1===f&&(f=4294967295);f=Ha(c);var g=k=>k;if(0===d){var n=32-8*c;g=k=>k<<n>>>n}c=b.includes("unsigned")?function(k,h){return h>>>0}:function(k,h){return h};U(a,{name:b,fromWireType:g,
toWireType:c,argPackAdvance:8,readValueFromPointer:fb(b,f,0!==d),B:null})},a:function(a,b,c){function d(g){g>>=2;var n=I;return new f(ta,n[g+1],n[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);U(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{G:!0})},g:function(a,b){b=P(b);var c="std::string"===b;U(a,{name:b,fromWireType:function(d){var f=I[d>>2];if(c)for(var g=d+4,n=0;n<=f;++n){var k=d+4+n;if(n==f||0==C[k]){if(g){var h=
g;var p=C,q=h+(k-g);for(g=h;p[g]&&!(g>=q);)++g;if(16<g-h&&p.subarray&&ka)h=ka.decode(p.subarray(h,g));else{for(q="";h<g;){var m=p[h++];if(m&128){var r=p[h++]&63;if(192==(m&224))q+=String.fromCharCode((m&31)<<6|r);else{var x=p[h++]&63;m=224==(m&240)?(m&15)<<12|r<<6|x:(m&7)<<18|r<<12|x<<6|p[h++]&63;65536>m?q+=String.fromCharCode(m):(m-=65536,q+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else q+=String.fromCharCode(m)}h=q}}else h="";if(void 0===l)var l=h;else l+=String.fromCharCode(0),l+=h;g=k+
1}}else{l=Array(f);for(n=0;n<f;++n)l[n]=String.fromCharCode(C[d+4+n]);l=l.join("")}W(d);return l},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||T("Cannot pass non-string to std::string");var n=(c&&g?()=>{for(var p=0,q=0;q<f.length;++q){var m=f.charCodeAt(q);55296<=m&&57343>=m&&(m=65536+((m&1023)<<10)|f.charCodeAt(++q)&1023);127>=m?++p:p=2047>=m?p+2:65535>=m?p+3:
p+4}return p}:()=>f.length)(),k=jb(4+n+1);I[k>>2]=n;if(c&&g)la(f,k+4,n+1);else if(g)for(g=0;g<n;++g){var h=f.charCodeAt(g);255<h&&(W(k),T("String has UTF-16 code units that do not fit in 8 bits"));C[k+4+g]=h}else for(g=0;g<n;++g)C[k+4+g]=f[g];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:Ta,B:function(d){W(d)}})},c:function(a,b,c){c=P(c);if(2===b){var d=na;var f=oa;var g=pa;var n=()=>D;var k=1}else 4===b&&(d=qa,f=ra,g=sa,n=()=>I,k=2);U(a,{name:c,fromWireType:function(h){for(var p=
I[h>>2],q=n(),m,r=h+4,x=0;x<=p;++x){var l=h+4+x*b;if(x==p||0==q[l>>k])r=d(r,l-r),void 0===m?m=r:(m+=String.fromCharCode(0),m+=r),r=l+b}W(h);return m},toWireType:function(h,p){"string"!==typeof p&&T("Cannot pass non-string to C++ string type "+c);var q=g(p),m=jb(4+q+b);I[m>>2]=q>>k;f(p,m+4,q+b);null!==h&&h.push(W,m);return m},argPackAdvance:8,readValueFromPointer:Ta,B:function(h){W(h)}})},o:function(a,b){b=P(b);U(a,{J:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
h:function(){B("")},n:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=gb();else return G[kb()>>2]=28,-1;G[b>>2]=a/1E3|0;G[b+4>>2]=a%1E3*1E6|0;return 0},i:function(a,b,c){C.copyWithin(a,b,b+c)},d:function(){B("OOM")},m:X};
(function(){function a(f){e.asm=f.exports;ia=e.asm.p;ta=f=ia.buffer;e.HEAP8=H=new Int8Array(f);e.HEAP16=E=new Int16Array(f);e.HEAP32=G=new Int32Array(f);e.HEAPU8=C=new Uint8Array(f);e.HEAPU16=D=new Uint16Array(f);e.HEAPU32=I=new Uint32Array(f);e.HEAPF32=ua=new Float32Array(f);e.HEAPF64=va=new Float64Array(f);wa=e.asm.v;ya.unshift(e.asm.q);J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ba&&(clearInterval(Ba),Ba=null),L&&(f=L,L=null,f()))}function b(f){a(f.instance)}function c(f){return Fa().then(function(g){return WebAssembly.instantiate(g,
d)}).then(function(g){return g}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:lb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||Ca()||M.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.q).apply(null,arguments)};var db=e.___getTypeName=function(){return(db=e.___getTypeName=e.asm.r).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.s).apply(null,arguments)};
var kb=e.___errno_location=function(){return(kb=e.___errno_location=e.asm.t).apply(null,arguments)},jb=e._malloc=function(){return(jb=e._malloc=e.asm.u).apply(null,arguments)},W=e._free=function(){return(W=e._free=e.asm.w).apply(null,arguments)},Z;L=function mb(){Z||nb();Z||(L=mb)};
function nb(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!ja)){Ga(ya);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();za.unshift(b)}Ga(za)}}if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Aa();Ga(xa);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=nb;
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();nb();


  return CppBenchmark.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = CppBenchmark;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return CppBenchmark; });
else if (typeof exports === 'object')
  exports["CppBenchmark"] = CppBenchmark;
